version: "3.8"
name: "async_etcd3gw"
services:

  etcd:
    image: "quay.io/coreos/etcd:v3.5.8"
    hostname: "etcd"
    network_mode: "host"
    ports:
      - "2379:2379"
    expose:
      - "2379"
    command:
      - /usr/local/bin/etcd
      - -name
      - etcd
      - --data-dir
      - /etcd_data
      - -advertise-client-urls
      - http://127.0.0.1:2379,http://127.0.0.1:4001
      - -listen-client-urls
      - http://0.0.0.0:2379
      - -initial-advertise-peer-urls
      - http://127.0.0.1:2380
      - -listen-peer-urls
      - http://0.0.0.0:2380
      - -initial-cluster-state
      - new

  etcd-browser:
    image: "rustyx/etcdv3-browser"
    hostname: "etcd-browser"
    network_mode: "host"
    ports:
      - "8081:8081"
    expose:
      - "8081"
    environment:
      - ETCD=127.0.0.1:2379
      - EDITABLE=1
