name: Tests

on:
  push:
  pull_request:

jobs:
  tests:
    name: Run tests (Python ${{matrix.python}}, etcd ${{matrix.etcd}})

    strategy:
      matrix:
        python: [ "3.9", "3.10", "3.11" ]
        etcd: [ "v3.5.8" ]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up etcd
      run: |
        curl -L https://github.com/etcd-io/etcd/releases/download/${{ matrix.etcd }}/etcd-${{ matrix.etcd }}-linux-amd64.tar.gz -o /tmp/etcd-${{ matrix.etcd }}-linux-amd64.tar.gz
        mkdir -p /tmp/etcd /tmp/etcd_data
        tar xzvf /tmp/etcd-${{ matrix.etcd }}-linux-amd64.tar.gz -C /tmp/etcd --strip-components=1
        rm -f /tmp/etcd-${{ matrix.etcd }}-linux-amd64.tar.gz
        /tmp/etcd/etcd --name etcd --data-dir /tmp/etcd_data --advertise-client-urls http://127.0.0.1:2379 --listen-client-urls http://127.0.0.1:2379 --initial-advertise-peer-urls http://127.0.0.1:2380 --listen-peer-urls http://0.0.0.0:2380 --initial-cluster-state new &

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}

    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-python-${{ matrix.python }}-pip-${{ hashFiles('**/requirements*.txt') }}-git-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-python-${{ matrix.python }}-pip-${{ hashFiles('**/requirements*.txt') }}
          ${{ runner.os }}-python-${{ matrix.python }}-pip-
          ${{ runner.os }}-python-${{ matrix.python }}-
          ${{ runner.os }}-python
          ${{ runner.os }}-

    - name: Upgrade pip and install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools wheel
        python -m pip install -r requirements.txt
        python -m pip install pytest pytest-asyncio

    - name: Run tests
      run: pytest

  all_done:
    name: Tests done
    runs-on: ubuntu-latest
    needs: [tests]

    steps:
      - name: All done
        run: echo 1
